### PR TITLE
Fixed incorrect reservation dates

### LINKED ISSUE #148: Receiving/Inserting date (Possible issue:Timezone displaying one day ahead)
**Describe the bug**
When receiving the date from the API (endpoint: /reservation/{reservationID}), the date received is the previous to the day inserted. 

**To Reproduce**
1. Create a booking for KFC with X date
2. Copy the reference ID
3. Go to the edit ID in the edit booking
4. The date there will be a day previous to the one you entered

**Expected behavior**
The dates are the same.

### PR DESCRIPTION
**Pull request by mitchfaulcon**
## Link to Issue Number
Closes #148

## Description
Dates of reservations are now displayed in the correct timezone rather than UTC, fixing issues that this was causing with editing & deleting reservations. Times are also now displayed nicely on the view all reservations page.

## Checklist
- [x] All feature request A/C have been met OR the bug has been fixed
- [ ] I ran all necessary tests and they pass
- [x] I rebased upstream/master onto my working branch before opening this PR
- [x] I have named my PR something sensible
- [x] I have included the issue number above
- [x] I have assigned at least two people to review my changes

## Other Notes
These changes can be viewed from the reservations screen as the edit reservation functionality currently seems broken

### CODE REVIEW

File: frontend/src/restaurant/RestaurantViewBookingPage.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ const RestaurantViewBookingPage = (props) => {
         <span className={style.bookingCode}>{`Booking Code: ${id}`}</span>
       </div>
       <div>
-        <span className={style.date}>{`${date}`}</span>
+        <span className={style.date}>{`${date.substring(0,10)}`}</span>
```
Comment (JedLJRobertson) [inline frontend/src/restaurant/RestaurantViewBookingPage.js:70]: Would be nice to comment this, but otherwise LGTM!
